server:
  port: 8080
  servlet:
    context-path: /mallDemo

spring:
  application:
    name: mall-demo
  datasource:
    name: mall-demo
    url: jdbc:mysql://192.168.161.114:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: malldata
    password: Admin@123
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-total: 20
  redis:
    # Redis服务器地址
    host: 192.168.161.114
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6378
    # Redis服务器连接密码（默认为空）
    password: Admin@123
    # 连接超时时间
    #timeout: 1000ms
    # 连接池
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0


# mybatis 配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.studies.mall.mapper

# 配置打印SQL
logging:
  level:
    com.studies.mall.mapper: debug

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

